#########################################################
# Specify the name of the target executable

TARGETS:=fimp

#########################################################
# Include common Makefile

include ../makefile_common.mk
