#########################################################
# Specify the name of the target executable

TARGETS:=onlybPlast

#########################################################
# Include common Makefile

include ../makefile_common.mk
