#########################################################
# Specify the name of the target executable

TARGETS:=lisaext

#########################################################
# Include common Makefile

include ../makefile_common.mk
