#########################################################
# Specify the name of the target executable

TARGETS:=onlyBGO

#########################################################
# Include common Makefile

include ../makefile_common.mk
