#########################################################
# Specify the name of the target executable

TARGETS:=NovTest

#########################################################
# Include common Makefile

include ../makefile_common.mk
