#########################################################
# Specify the name of the target executable

TARGETS:=hispec10

#########################################################
# Include common Makefile

include ../makefile_common.mk
