#########################################################
# Specify the name of the target executable

TARGETS:=s115

#########################################################
# Include common Makefile

include ../makefile_common.mk
