#########################################################
# Specify the name of the target executable

TARGETS:=pareeksha

#########################################################
# Include common Makefile

include ../makefile_common.mk
