#########################################################
# Specify the name of the target executable

TARGETS:=template

#########################################################
# Include common Makefile

include ../makefile_common.mk
