#########################################################
# Specify the name of the target executable

TARGETS:=onlyFATIMA

#########################################################
# Include common Makefile

include ../makefile_common.mk
