#########################################################
# Specify the name of the target executable

TARGETS:=s100

#########################################################
# Include common Makefile

include ../makefile_common.mk
