#########################################################
# Specify the name of the target executable

TARGETS:=beammonitor

#########################################################
# Include common Makefile

include ../makefile_common.mk
