#########################################################
# Specify the name of the target executable

TARGETS:=test

#########################################################
# Include common Makefile

include ../makefile_common.mk
