#########################################################
# Specify the name of the target executable

TARGETS:=s101

#########################################################
# Include common Makefile

include ../makefile_common.mk
