#########################################################
# Specify the name of the target executable

TARGETS:=febex

#########################################################
# Include common Makefile

include ../makefile_common.mk
