#########################################################
# Specify the name of the target executable

TARGETS:=s143y2025

#########################################################
# Include common Makefile

include ../makefile_common.mk
