/** BEGIN_ACCOUNT_IDS **************************************************
 *
 * Structure and identifier for raw data items.
 *
 * Do not edit - automatically generated.
 */

account_id _account_ids[] =
{ 
  { 0, "FEBEX_EVENT", "sumchannel" },
  { 1, "FEBEX_EVENT", "channel_size" },
  { 2, "FEBEX_EVENT", "event_timestamp_hi" },
  { 3, "FEBEX_EVENT", "event_timestamp_lo" },
  { 4, "FEBEX_EVENT", "hp" },
  { 5, "FEBEX_EVENT", "deadbeef" },
  { 6, "FEBEX_EVENT", "channelids" },
  { 7, "FEBEX_EVENT", "channel_ts" },
  { 8, "FEBEX_EVENT", "chan_enrgy" },
  { 9, "FEBEX_EVENT", "future_use" },
  { 10, "FEBEX_EVENT", "sumchannel" },
  { 11, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 12, "FEBEX_EVENT_TRACES", "channel_size" },
  { 13, "FEBEX_EVENT_TRACES", "event_timestamp_hi" },
  { 14, "FEBEX_EVENT_TRACES", "event_timestamp_lo" },
  { 15, "FEBEX_EVENT_TRACES", "hp" },
  { 16, "FEBEX_EVENT_TRACES", "deadbeef" },
  { 17, "FEBEX_EVENT_TRACES", "channelids" },
  { 18, "FEBEX_EVENT_TRACES", "channel_ts" },
  { 19, "FEBEX_EVENT_TRACES", "chan_enrgy" },
  { 20, "FEBEX_EVENT_TRACES", "future_use" },
  { 21, "FEBEX_EVENT_TRACES", "header" },
  { 22, "FEBEX_EVENT_TRACES", "tracesize" },
  { 23, "FEBEX_EVENT_TRACES", "tracehead" },
  { 24, "FEBEX_EVENT_TRACES", "channel_trace" },
  { 25, "FEBEX_EVENT_TRACES", "trace_trailer" },
  { 26, "FEBEX_EVENT_TRACES", "header" },
  { 27, "FEBEX_EVENT_TRACES", "tracesize" },
  { 28, "FEBEX_EVENT_TRACES", "tracehead" },
  { 29, "FEBEX_EVENT_TRACES", "trace_trailer" },
  { 30, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 31, "FEBEX_PADDING", "pads_data" },
  { 32, "FEBEX_PADDING", "pads_data" },
  { 33, "TAMEX4_EPOCH_DATA", "data" },
  { 34, "TAMEX4_EPOCH_DATA", "data" },
  { 35, "TAMEX4_HEADER", "trigger_window" },
  { 36, "TAMEX4_HEADER", "trigger_window" },
  { 37, "TAMEX4_PADDING", "padding" },
  { 38, "TAMEX4_PADDING", "padding" },
  { 39, "TAMEX4_TIME_DATA", "data" },
  { 40, "TAMEX4_TIME_DATA", "data" },
  { 41, "TAMEX4_SFP", "indicator" },
  { 42, "TAMEX4_SFP", "data_size" },
  { 43, "TAMEX4_SFP", "tdc_header" },
  { 44, "TAMEX4_SFP", "error_bits" },
  { 45, "TAMEX4_SFP", "trailer" },
  { 46, "TAMEX4_SFP", "indicator" },
  { 47, "TIMESTAMP_WHITERABBIT", "header" },
  { 48, "TIMESTAMP_WHITERABBIT", "d1" },
  { 49, "TIMESTAMP_WHITERABBIT", "d2" },
  { 50, "TIMESTAMP_WHITERABBIT", "d3" },
  { 51, "TIMESTAMP_WHITERABBIT", "d4" },
  { 52, "TIMESTAMP_WHITERABBIT", "header" },
  { 53, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 54, "TIMESTAMP_WHITERABBIT_EXTENDED", "d1" },
  { 55, "TIMESTAMP_WHITERABBIT_EXTENDED", "d2" },
  { 56, "TIMESTAMP_WHITERABBIT_EXTENDED", "d3" },
  { 57, "TIMESTAMP_WHITERABBIT_EXTENDED", "d4" },
  { 58, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 59, "WR_MULTI", "hi" },
  { 60, "WR_MULTI", "lo" },
  { 61, "WR_MULTI", "hi" },
};

#define NUM_ACCOUNT_IDS  62

/** END_ACCOUNT_IDS ***************************************************/
