/** BEGIN_ACCOUNT_IDS **************************************************
 *
 * Structure and identifier for raw data items.
 *
 * Do not edit - automatically generated.
 */

account_id _account_ids[] =
{ 
  { 0, "BARRIER", "barrier" },
  { 1, "BARRIER", "barrier" },
  { 2, "DUMMY", "no" },
  { 3, "DUMMY", "no" },
  { 4, "FEBEX_BAD_EVENT", "bad" },
  { 5, "FEBEX_BAD_EVENT", "bad" },
  { 6, "FEBEX_EVENT", "sumchannel" },
  { 7, "FEBEX_EVENT", "channel_size" },
  { 8, "FEBEX_EVENT", "event_timestamp_hi" },
  { 9, "FEBEX_EVENT", "event_timestamp_lo" },
  { 10, "FEBEX_EVENT", "hp" },
  { 11, "FEBEX_EVENT", "deadbeef" },
  { 12, "FEBEX_EVENT", "channelids" },
  { 13, "FEBEX_EVENT", "channel_ts" },
  { 14, "FEBEX_EVENT", "chan_enrgy" },
  { 15, "FEBEX_EVENT", "future_use" },
  { 16, "FEBEX_EVENT", "sumchannel" },
  { 17, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 18, "FEBEX_EVENT_TRACES", "channel_size" },
  { 19, "FEBEX_EVENT_TRACES", "event_timestamp_hi" },
  { 20, "FEBEX_EVENT_TRACES", "event_timestamp_lo" },
  { 21, "FEBEX_EVENT_TRACES", "hp" },
  { 22, "FEBEX_EVENT_TRACES", "deadbeef" },
  { 23, "FEBEX_EVENT_TRACES", "channelids" },
  { 24, "FEBEX_EVENT_TRACES", "channel_ts" },
  { 25, "FEBEX_EVENT_TRACES", "chan_enrgy" },
  { 26, "FEBEX_EVENT_TRACES", "future_use" },
  { 27, "FEBEX_EVENT_TRACES", "header" },
  { 28, "FEBEX_EVENT_TRACES", "tracesize" },
  { 29, "FEBEX_EVENT_TRACES", "tracehead" },
  { 30, "FEBEX_EVENT_TRACES", "channel_trace" },
  { 31, "FEBEX_EVENT_TRACES", "trace_trailer" },
  { 32, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 33, "FEBEX_PADDING", "pads_data" },
  { 34, "FEBEX_PADDING", "pads_data" },
  { 35, "VME_CAEN_V830_FRS", "v830_header" },
  { 36, "VME_CAEN_V830_FRS", "data_word" },
  { 37, "VME_CAEN_V830_FRS", "v830_header" },
  { 38, "ZERO_FILLER", "filler" },
  { 39, "ZERO_FILLER", "filler" },
  { 40, "VME_CAEN_V792_FRS", "v792_header" },
  { 41, "VME_CAEN_V792_FRS", "adc_data" },
  { 42, "VME_CAEN_V792_FRS", "eob" },
  { 43, "VME_CAEN_V792_FRS", "eob2" },
  { 44, "VME_CAEN_V792_FRS", "v792_header" },
  { 45, "TDC_HEADER", "tdc_header" },
  { 46, "TDC_HEADER", "tdc_header" },
  { 47, "TDC_DATA_V1290", "tdc_data" },
  { 48, "TDC_DATA_V1290", "tdc_data" },
  { 49, "TDC_ERROR", "tdc_err" },
  { 50, "TDC_ERROR", "tdc_err" },
  { 51, "TDC_TRAILER", "tdc_trailer" },
  { 52, "TDC_TRAILER", "tdc_trailer" },
  { 53, "VME_CAEN_V1290_FRS", "header" },
  { 54, "VME_CAEN_V1290_FRS", "ext_time_tag" },
  { 55, "VME_CAEN_V1290_FRS", "trailer" },
  { 56, "VME_CAEN_V1290_FRS", "eob" },
  { 57, "VME_CAEN_V1290_FRS", "header" },
  { 58, "MESYTEC_MQDC32_FRS", "header" },
  { 59, "MESYTEC_MQDC32_FRS", "ch_data" },
  { 60, "MESYTEC_MQDC32_FRS", "zero" },
  { 61, "MESYTEC_MQDC32_FRS", "end_of_event" },
  { 62, "MESYTEC_MQDC32_FRS", "header" },
  { 63, "MESYTEC_MTDC32_FRS", "header" },
  { 64, "MESYTEC_MTDC32_FRS", "zero" },
  { 65, "MESYTEC_MTDC32_FRS", "ch_data" },
  { 66, "MESYTEC_MTDC32_FRS", "end_of_event" },
  { 67, "MESYTEC_MTDC32_FRS", "header" },
  { 68, "SIS_3820_FRS", "custom_header" },
  { 69, "SIS_3820_FRS", "event" },
  { 70, "SIS_3820_FRS", "event" },
  { 71, "SIS_3820_FRS", "custom_header" },
  { 72, "TAMEX4_EPOCH_DATA", "data" },
  { 73, "TAMEX4_EPOCH_DATA", "data" },
  { 74, "TAMEX4_HEADER", "trigger_window" },
  { 75, "TAMEX4_HEADER", "trigger_window" },
  { 76, "TAMEX4_PADDING", "padding" },
  { 77, "TAMEX4_PADDING", "padding" },
  { 78, "TAMEX4_TIME_DATA", "data" },
  { 79, "TAMEX4_TIME_DATA", "data" },
  { 80, "TAMEX4_SFP", "indicator" },
  { 81, "TAMEX4_SFP", "data_size" },
  { 82, "TAMEX4_SFP", "tdc_header" },
  { 83, "TAMEX4_SFP", "error_bits" },
  { 84, "TAMEX4_SFP", "trailer" },
  { 85, "TAMEX4_SFP", "indicator" },
  { 86, "TDC_DATA_V1190", "tdc_data" },
  { 87, "TDC_DATA_V1190", "tdc_data" },
  { 88, "TIMESTAMP_WHITERABBIT", "header" },
  { 89, "TIMESTAMP_WHITERABBIT", "d1" },
  { 90, "TIMESTAMP_WHITERABBIT", "d2" },
  { 91, "TIMESTAMP_WHITERABBIT", "d3" },
  { 92, "TIMESTAMP_WHITERABBIT", "d4" },
  { 93, "TIMESTAMP_WHITERABBIT", "header" },
  { 94, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 95, "TIMESTAMP_WHITERABBIT_EXTENDED", "d1" },
  { 96, "TIMESTAMP_WHITERABBIT_EXTENDED", "d2" },
  { 97, "TIMESTAMP_WHITERABBIT_EXTENDED", "d3" },
  { 98, "TIMESTAMP_WHITERABBIT_EXTENDED", "d4" },
  { 99, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 100, "VME_CAEN_V7X5_FRS", "header" },
  { 101, "VME_CAEN_V7X5_FRS", "ch_data" },
  { 102, "VME_CAEN_V7X5_FRS", "eob" },
  { 103, "VME_CAEN_V7X5_FRS", "eob2" },
  { 104, "VME_CAEN_V7X5_FRS", "header" },
  { 105, "VME_CAEN_V1190_FRS", "header" },
  { 106, "VME_CAEN_V1190_FRS", "second1" },
  { 107, "VME_CAEN_V1190_FRS", "real_header" },
  { 108, "VME_CAEN_V1190_FRS", "ext_time_tag" },
  { 109, "VME_CAEN_V1190_FRS", "trailer" },
  { 110, "VME_CAEN_V1190_FRS", "eob" },
  { 111, "VME_CAEN_V1190_FRS", "header" },
  { 112, "TRIG3EVENT", "trig3" },
  { 113, "TRIG3EVENT", "trig3" },
  { 114, "VFTX2", "custom_header" },
  { 115, "VFTX2", "trigger_window" },
  { 116, "VFTX2", "status_register" },
  { 117, "VFTX2", "mvlc_header" },
  { 118, "VFTX2", "skip_event_header" },
  { 119, "VFTX2", "event" },
  { 120, "VFTX2", "custom_header" },
  { 121, "WR_MULTI", "hi" },
  { 122, "WR_MULTI", "lo" },
  { 123, "WR_MULTI", "hi" },
};

#define NUM_ACCOUNT_IDS  124

/** END_ACCOUNT_IDS ***************************************************/
