#########################################################
# Specify the name of the target executable

TARGETS:=s143

#########################################################
# Include common Makefile

include ../makefile_common.mk
