/** BEGIN_ACCOUNT_IDS **************************************************
 *
 * Structure and identifier for raw data items.
 *
 * Do not edit - automatically generated.
 */

account_id _account_ids[] =
{ 
  { 0, "BAD_EVENT", "be" },
  { 1, "BAD_EVENT", "be" },
  { 2, "DUMMY", "no" },
  { 3, "DUMMY", "no" },
  { 4, "FEBEX_EVENT", "sumchannel" },
  { 5, "FEBEX_EVENT", "channel_size" },
  { 6, "FEBEX_EVENT", "event_timestamp_hi" },
  { 7, "FEBEX_EVENT", "event_timestamp_lo" },
  { 8, "FEBEX_EVENT", "hp" },
  { 9, "FEBEX_EVENT", "deadbeef" },
  { 10, "FEBEX_EVENT", "channelids" },
  { 11, "FEBEX_EVENT", "channel_ts" },
  { 12, "FEBEX_EVENT", "chan_enrgy" },
  { 13, "FEBEX_EVENT", "future_use" },
  { 14, "FEBEX_EVENT", "sumchannel" },
  { 15, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 16, "FEBEX_EVENT_TRACES", "channel_size" },
  { 17, "FEBEX_EVENT_TRACES", "event_timestamp_hi" },
  { 18, "FEBEX_EVENT_TRACES", "event_timestamp_lo" },
  { 19, "FEBEX_EVENT_TRACES", "hp" },
  { 20, "FEBEX_EVENT_TRACES", "deadbeef" },
  { 21, "FEBEX_EVENT_TRACES", "channelids" },
  { 22, "FEBEX_EVENT_TRACES", "channel_ts" },
  { 23, "FEBEX_EVENT_TRACES", "chan_enrgy" },
  { 24, "FEBEX_EVENT_TRACES", "future_use" },
  { 25, "FEBEX_EVENT_TRACES", "header" },
  { 26, "FEBEX_EVENT_TRACES", "tracesize" },
  { 27, "FEBEX_EVENT_TRACES", "tracehead" },
  { 28, "FEBEX_EVENT_TRACES", "channel_trace" },
  { 29, "FEBEX_EVENT_TRACES", "trace_trailer" },
  { 30, "FEBEX_EVENT_TRACES", "sumchannel" },
  { 31, "FEBEX_PADDING", "pads_data" },
  { 32, "FEBEX_PADDING", "pads_data" },
  { 33, "TAMEX4_EPOCH_DATA", "data" },
  { 34, "TAMEX4_EPOCH_DATA", "data" },
  { 35, "TAMEX4_HEADER", "trigger_window" },
  { 36, "TAMEX4_HEADER", "trigger_window" },
  { 37, "TAMEX4_PADDING", "padding" },
  { 38, "TAMEX4_PADDING", "padding" },
  { 39, "TAMEX4_TIME_DATA", "data" },
  { 40, "TAMEX4_TIME_DATA", "data" },
  { 41, "TAMEX4_SFP", "indicator" },
  { 42, "TAMEX4_SFP", "data_size" },
  { 43, "TAMEX4_SFP", "tdc_header" },
  { 44, "TAMEX4_SFP", "error_bits" },
  { 45, "TAMEX4_SFP", "trailer" },
  { 46, "TAMEX4_SFP", "indicator" },
  { 47, "TIMESTAMP_WHITERABBIT", "header" },
  { 48, "TIMESTAMP_WHITERABBIT", "d1" },
  { 49, "TIMESTAMP_WHITERABBIT", "d2" },
  { 50, "TIMESTAMP_WHITERABBIT", "d3" },
  { 51, "TIMESTAMP_WHITERABBIT", "d4" },
  { 52, "TIMESTAMP_WHITERABBIT", "header" },
  { 53, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 54, "TIMESTAMP_WHITERABBIT_EXTENDED", "d1" },
  { 55, "TIMESTAMP_WHITERABBIT_EXTENDED", "d2" },
  { 56, "TIMESTAMP_WHITERABBIT_EXTENDED", "d3" },
  { 57, "TIMESTAMP_WHITERABBIT_EXTENDED", "d4" },
  { 58, "TIMESTAMP_WHITERABBIT_EXTENDED", "header" },
  { 59, "VME_CAEN_V1751", "board_agg_size" },
  { 60, "VME_CAEN_V1751", "board_details" },
  { 61, "VME_CAEN_V1751", "board_agg_counter" },
  { 62, "VME_CAEN_V1751", "board_agg_timetag" },
  { 63, "VME_CAEN_V1751", "channel_agg_size" },
  { 64, "VME_CAEN_V1751", "format_one" },
  { 65, "VME_CAEN_V1751", "format_two" },
  { 66, "VME_CAEN_V1751", "channel_time_tag" },
  { 67, "VME_CAEN_V1751", "extras" },
  { 68, "VME_CAEN_V1751", "extras" },
  { 69, "VME_CAEN_V1751", "extras" },
  { 70, "VME_CAEN_V1751", "extras" },
  { 71, "VME_CAEN_V1751", "extras" },
  { 72, "VME_CAEN_V1751", "channel_time_tag" },
  { 73, "VME_CAEN_V1751", "qdata" },
  { 74, "VME_CAEN_V1751", "board_agg_size" },
  { 75, "WR_MULTI", "hi" },
  { 76, "WR_MULTI", "lo" },
  { 77, "WR_MULTI", "hi" },
};

#define NUM_ACCOUNT_IDS  78

/** END_ACCOUNT_IDS ***************************************************/
