#########################################################
# Specify the name of the target executable

TARGETS:=gsiscanner

#########################################################
# Include common Makefile

include ../makefile_common.mk
