#########################################################
# Specify the name of the target executable

TARGETS:=s452

#########################################################
# Include common Makefile

include ../makefile_common.mk
