// -*- C++ -*-

#include "../../common/whiterabbit.spec"
#include "../../common/frs.spec"
#include "../../common/ge_febex.spec" // gsi_febex4.spec
#include "../../common/gsi_tamex4.spec"
#include "config/setup.hh" // ../../../config/s452

// one by one we will remove all but AIDA...


external EXT_PLASTIC_TP();
external EXT_PLASTIC();
external EXT_AIDA();

DUMMY()
{
    UINT32 no NOENCODE;
}

SUBEVENT(aida_subev)
{   

    if (AIDA_USED)
    {
        ts = TIMESTAMP_WHITERABBIT(id=0x700);
        external data = EXT_AIDA();
    }
    else
    {
        select several
        {
            dummy = DUMMY();
        }
        
    }
}

SUBEVENT(germanium_subev)
{
    ts = TIMESTAMP_WHITERABBIT(id=0x400); // can be autogenerated or simply in config.

    select several
    {
        padding = FEBEX_PADDING();
    }
    select several
    {   // do once per card
        data = FEBEX_EVENT();
    }
}


SUBEVENT(fatima_tamex_subev)
{
    ts = TIMESTAMP_WHITERABBIT(id=0x500);
    trigger_window = TAMEX4_HEADER();
    select several 
    {
        padding = TAMEX4_PADDING();
    }
    select several
    {
        tamex[0] = TAMEX4_SFP(sfp=0,card=0);
        tamex[1] = TAMEX4_SFP(sfp=0,card=1);
        tamex[2] = TAMEX4_SFP(sfp=0,card=2);
        tamex[3] = TAMEX4_SFP(sfp=0,card=3);
        tamex[4] = TAMEX4_SFP(sfp=0,card=4);
        tamex[5] = TAMEX4_SFP(sfp=0,card=5);
        tamex[6] = TAMEX4_SFP(sfp=0,card=6);
        tamex[7] = TAMEX4_SFP(sfp=0,card=7);
        tamex[8] = TAMEX4_SFP(sfp=0,card=8);
    }
}
/*
SUBEVENT(plastic_subev)
{
    //MEMBER(DATA12 am_fired[32] ZERO_SUPPRESS_MULTI(200));

    if (BPLAST_USED)
    {
        ts = TIMESTAMP_WHITERABBIT(id=0x500);
        if (IS_PLASTIC_TWINPEAKS)
        {
            external data_tp = EXT_PLASTIC_TP();
        }
        else
        {
            
            // can probably be written even MORE nicely!!
            trigger_window = TAMEX_WINDOW();
            select several 
            {
                padding = TAMEX_PADDING();
            }
            select several
            {
                tamex[0] = TAMEX_DATA(card = 0);
                tamex[1] = TAMEX_DATA(card = 1);
                tamex[2] = TAMEX_DATA(card = 2);
            }

        
            //external data = EXT_PLASTIC();
              
        }

    }
    else
    {
        select several
        {
            dummy = DUMMY();
        }
    }

}*/

SUBEVENT(frs_whiterabbit_subev)
{
    if (FRS_USED && WR_USED)
    {   
        ts = TIMESTAMP_WHITERABBIT(id=0x100);
    }
    else
    {
        select several
        {
            dummy = DUMMY();
        }
    }
}

SUBEVENT(frs_main_crate_subev)
{
    if (FRS_USED)
    {   
        data = MAIN_CRATE_DATA();
    }
    else
    {
        select several
        {
            dummy = DUMMY();
        }
    }
}

SUBEVENT(frs_tpat_subev)
{
    if (FRS_USED)
    {
        data = TPAT_DATA(id=0xCF);
    }
    else
    {
        select several
        {
            dummy = DUMMY();
        }
    }
}

SUBEVENT(frs_crate_subev)
{
    if (FRS_USED)
    {
        frs = FRS_DATA();
    }
    else
    {
        dummy = DUMMY();
    }
}


SUBEVENT (frs_tpc_crate_subev)
{
    if (FRS_USED)
    {
        tpc = TPC_DATA();
    }
    else
    {
        dummy = DUMMY();
    }
}

SUBEVENT(frs_tof_crate_subev)
{   
    if (FRS_USED)
    {
        data = TOF_DATA(); // 
    }
    else
    {
        dummy = DUMMY();
    }
}

EVENT
{
    //revisit aida = aida_subev(type = 10, subtype = 1, procid = 90, control = 37);
    //germanium = germanium_subev(type = 10, subtype = 1, procid = 60, control = 20);
    //fatima_vme = fatima_vme_subev(type = 10, subtype = 1, procid = 70, control = 20, subcrate = 0);
    fatima = fatima_tamex_subev(type = 10, subtype = 1, procid = 80, control = 20, subcrate = 0);
    //plastic = plastic_subev(type = 10, subtype = 1, procid = 80, control = 20, subcrate = 0);

    // frs stuff
    // all works as spec but needs a major cleanup
    //frs_whiterabbit = frs_whiterabbit_subev(type = 10, subtype = 1, procid = 10, control = 20); // whiterabbit
    //frs_main_crate = frs_main_crate_subev(type = 12, subtype = 1, procid = 10, control = 20); // main crate
    //frs_tpat = frs_tpat_subev(type = 36, subtype = 3600, procid = 10, control = 20); // tpat // works
    //frs_tof_crate = frs_tof_crate_subev(type = 12, subtype = 1, procid = 35, control = 20); // VFTX, MQDC, SIS 3820
    //frs_tpc_crate = frs_tpc_crate_subev(type = 12, subtype = 1, procid = 20, control = 21); // frs_main_scaler // music?
    //frs_crate = frs_crate_subev(type = 12, subtype = 1, procid = 30, control = 20); // sci_tx? // "frs crate"? // scaler_frs is here*/


    ignore_unknown_subevent;
};

#include "mapping.hh"
