#########################################################
# Specify the name of the target executable

TARGETS:=tamex

#########################################################
# Include common Makefile

include ../makefile_common.mk
