// -*- C++ -*-

#include "config.spec"
#include "../../common/whiterabbit.spec"
#include "../../common/ge_febex.spec"

DUMMY()
{
    UINT32 no NOENCODE;
}


SUBEVENT(febex_subev_traces)
{
    //ts = TIMESTAMP_WHITERABBIT(id=0x400); // can be autogenerated or simply in config.

    select several
    {
        padding = FEBEX_PADDING();
    }
    select several
    {   // do once per card
        data = FEBEX_EVENT_TRACES();
    }


}

/*
SUBEVENT(febex_subev)
{
  // white rabbit
  if (withWR)
  {
    wr = TIMESTAMP_WHITERABBIT(id=0x400);
  }
  
  // padding (select several essential)
  select several
  {
    padding = FEBEX_PADDING();
  }
  
  data = FEBEX_TRACES();

}
*/

EVENT
{

  lisa = febex_subev_traces(procid = 60);

  ignore_unknown_subevent;
}

// for mapping UNPACK -> RAW
#include "mapping.hh"