#########################################################
# Specify the name of the target executable

TARGETS:=lisa

#########################################################
# Include common Makefile

include ../makefile_common.mk
