#########################################################
# Specify the name of the target executable

TARGETS:=implantationstacktest

#########################################################
# Include common Makefile

include ../makefile_common.mk