#########################################################
# Specify the name of the target executable

TARGETS:=gsiscannerv1751

#########################################################
# Include common Makefile

include ../makefile_common.mk
