#########################################################
# Specify the name of the target executable

TARGETS:=s181

#########################################################
# Include common Makefile

include ../makefile_common.mk
