#########################################################
# Specify the name of the target executable

TARGETS:=s450

#########################################################
# Include common Makefile

include ../makefile_common.mk
