#########################################################
# Specify the name of the target executable

TARGETS:=jikken

#########################################################
# Include common Makefile

include ../makefile_common.mk
