#define SIGNAL_FOOT(id) \
	SIGNAL(FOOTTS##id##_WR_LO, , DATA32);\
	SIGNAL(FOOTTS##id##_WR_HI, , DATA32);\
	SIGNAL(FOOTTSS##id, , DATA12);\
	SIGNAL(ZERO_SUPPRESS: FOOT##id##_640);\
	SIGNAL(FOOT##id##_640_E, , DATA16)

SIGNAL_FOOT( 1);
SIGNAL_FOOT( 2);
SIGNAL_FOOT( 3);
SIGNAL_FOOT( 4);
SIGNAL_FOOT( 5);
SIGNAL_FOOT( 6);
SIGNAL_FOOT( 7);
SIGNAL_FOOT( 8);
